-- =====================================================================
--  טבלת המוצרים לדף "קישור בביו" של לקוח/ה  (תבנית link-in-bio)
-- =====================================================================
--  איך משתמשים:
--  1. החליפי בכל הקובץ את physiomation בקידומת שבחרת (אותו ערך כמו SITE_PREFIX
--     בקובץ index.html). בעורך טקסט: "החלף הכל" על physiomation.
--     לדוגמה:  physiomation  ->  dana
--  2. פתחי את ה-SQL Editor בפרויקט ה-Supabase של הלקוח/ה והדביקי הכל.
--  3. לחצי Run. נוצרת טבלה אחת שמשרתת רק את הדף הזה.
--
--  הערה: הדף שומר בטבלה הזו גם "שורת הגדרות" מיוחדת (category='_meta')
--  שמכילה את תמונת הפרופיל, הרקע, שמות המגירות, ההסברים והאייקונים —
--  אין צורך בטבלה נוספת.
-- =====================================================================

create table if not exists physiomation_products (
  id          bigint generated by default as identity primary key,
  category    text not null,   -- cat1 | cat2 | cat3 | cat4 | _meta
  title       text not null,
  description text,
  url         text not null,
  image       text,
  sort_order  int  default 0,
  created_at  timestamptz default now()
);

-- הרשאות: הדף קורא/כותב עם המפתח הציבורי; הניהול מוגן בסיסמה בצד הדפדפן.
alter table physiomation_products enable row level security;

create policy "physiomation_products_all"
  on physiomation_products for all
  to anon, authenticated
  using (true) with check (true);
