-- =====================================================================
--  טבלאות של דף "יועצות ההנקה של אילת"  (sites/yoatsot-eilat)
-- =====================================================================
--  הערה: זהו הדף הראשון, ולכן הטבלאות שלו נקראות בשם הפשוט
--  consultants / pending_consultants (בלי קידומת) — כך הן נוצרו במקור.
--  הדף החי כבר משתמש בהן, ולכן אנחנו לא משנים את שמן.
--
--  כל דף *חדש* יקבל קידומת משלו (ראי _template-new-site/tables.sql),
--  כך שאף דף לא נוגע במידע של דף אחר.
--
--  הקובץ הזה הוא תיעוד בלבד — הטבלאות כבר קיימות ב-Supabase.
-- =====================================================================

create table if not exists consultants (
  id               bigint generated by default as identity primary key,
  name             text not null,
  credentials      text,
  statement        text,
  location         text,
  channels         jsonb default '{}'::jsonb,
  additional_fields text,
  phone            text,
  image            text,
  instagram        text,
  facebook         text,
  website          text,
  status           text default 'approved',
  created_at       timestamptz default now()
);

create table if not exists pending_consultants (
  id               bigint generated by default as identity primary key,
  name             text not null,
  credentials      text,
  statement        text,
  location         text,
  channels         jsonb default '{}'::jsonb,
  additional_fields text,
  phone            text,
  image            text,
  instagram        text,
  facebook         text,
  website          text,
  status           text default 'pending',
  created_at       timestamptz default now()
);
