-- =====================================================================
--  טבלאות Supabase לדף נחיתה חדש
-- =====================================================================
--  איך משתמשים:
--  1. החליפי בכל הקובץ את __PREFIX__ בקידומת של הדף שלך
--     (אותו ערך שכתבת ב-SITE_PREFIX בקובץ index.html).
--     טיפ: בעורך טקסט עשי "החלף הכל" (Find & Replace) על __PREFIX__.
--     לדוגמה: __PREFIX__  ->  telaviv
--  2. פתחי את ה-SQL Editor ב-Supabase והדביקי את כל הקובץ.
--  3. לחצי Run. זהו — נוצרו שתי טבלאות שמשרתות רק את הדף הזה.
-- =====================================================================

-- ---------- טבלת היועצות המאושרות (מוצגות בדף הציבורי) ----------
create table if not exists __PREFIX___consultants (
  id               bigint generated by default as identity primary key,
  name             text not null,
  credentials      text,
  statement        text,
  location         text,
  channels         jsonb default '{}'::jsonb,
  additional_fields text,
  phone            text,
  image            text,
  instagram        text,
  facebook         text,
  website          text,
  status           text default 'approved',
  created_at       timestamptz default now()
);

-- ---------- טבלת בקשות ההצטרפות (ממתינות לאישור המנהלת) ----------
create table if not exists __PREFIX___pending_consultants (
  id               bigint generated by default as identity primary key,
  name             text not null,
  credentials      text,
  statement        text,
  location         text,
  channels         jsonb default '{}'::jsonb,
  additional_fields text,
  phone            text,
  image            text,
  instagram        text,
  facebook         text,
  website          text,
  status           text default 'pending',
  created_at       timestamptz default now()
);

-- =====================================================================
--  הרשאות גישה (RLS)
--  ההגדרה הזו מאפשרת לדף לקרוא/להוסיף/לעדכן/למחוק עם המפתח הציבורי,
--  בדיוק כמו שהדף הקיים עובד. פאנל הניהול מוגן בקוד סודי בצד הדפדפן.
-- =====================================================================
alter table __PREFIX___consultants          enable row level security;
alter table __PREFIX___pending_consultants  enable row level security;

create policy "__PREFIX___consultants_all"
  on __PREFIX___consultants for all
  to anon, authenticated
  using (true) with check (true);

create policy "__PREFIX___pending_all"
  on __PREFIX___pending_consultants for all
  to anon, authenticated
  using (true) with check (true);
