-- =====================================================================
--  טבלה לדף קישורי האפיליאייט (sites/affiliate)
-- =====================================================================
--  איך מריצים (פעם אחת בלבד):
--  1. היכנסי ל-Supabase → SQL Editor → New query
--  2. הדביקי את כל הקובץ הזה ולחצי Run
--  זהו — נוצרה טבלה אחת שמשרתת רק את דף האפיליאייט.
-- =====================================================================

create table if not exists affiliate_products (
  id          bigint generated by default as identity primary key,
  category    text not null,   -- relationships | pregnancy | breastfeeding | development
  title       text not null,
  description text,
  url         text not null,
  image       text,
  sort_order  int  default 0,
  created_at  timestamptz default now()
);

-- הרשאות: הדף קורא/כותב עם המפתח הציבורי; ממשק הניהול מוגן בסיסמה בצד הדפדפן.
alter table affiliate_products enable row level security;

create policy "affiliate_products_all"
  on affiliate_products for all
  to anon, authenticated
  using (true) with check (true);
